<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Salt State (SLS)</string>
	<key>uuid</key>
	<string>832BCE51-6DA0-4299-8321-007785A6EF0E</string>
	<key>fileTypes</key>
	<array>
		<string>sls</string>
	</array>

	<!-- Identical to YAML -->
	<key>foldingStartMarker</key>
	<string>^[^#]\s*.*:(\s*\[?| &amp;.+)?$</string>
	<key>foldingStopMarker</key>
	<string>^\s*$|^\s*\}|^\s*\]|^\s*\)</string>
	<key>keyEquivalent</key>
	<string>^~Y</string>

	<key>scopeName</key>
	<string>source.sls</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.jinja2</string>
		</dict>

		<!-- Highlighting of boolean constants -->
		<dict>
			<key>match</key>
			<string>((-)\s*)?((([\w\/][^\:\#]*)|(\"[\w\/][^\:\#]*\")|(\'[\w\/][^\:\#]*\'))(:))?\s*(?i)((true|false|yes|no)|(null|\~))(?-i)\s*(\#.*)?$</string>
			<key>name</key>
			<string>meta.tag.yaml</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.entry.yaml</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.yaml</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.yaml</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>string.quoted.single.yaml</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.yaml</string>
				</dict>
				<key>10</key>
				<dict>
					<key>name</key>
					<string>constant.boolean.yaml</string>
				</dict>
				<key>11</key>
				<dict>
					<key>name</key>
					<string>constant.null.yaml</string>
				</dict>
				<key>12</key>
				<dict>
					<key>name</key>
					<string>comment.line.yaml</string>
				</dict>
			</dict>
		</dict>

		<!-- Improve highlighting of numeric values -->
		<dict>
			<key>match</key>
			<string>((-)\s*)?((([\w\/][^\:\#]*)|(\"[\w\/][^\:\#]*\")|(\'[\w\/][^\:\#]*\'))(:))?\s*(((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)(L|l|UL|ul|u|U|F|f)?)\s*(\#.*)?$</string>
			<key>name</key>
			<string>meta.tag.yaml</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.entry.yaml</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.yaml</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.yaml</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>string.quoted.single.yaml</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.yaml</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.yaml</string>
				</dict>
				<key>20</key>
				<dict>
					<key>name</key>
					<string>comment.line.yaml</string>
				</dict>
			</dict>
		</dict>

		<!-- Improve highlighting of unquoted strings -->
		<dict>
			<key>match</key>
			<string>(?:(?:(-\s*)?([\w\/][^\:\#]*)\s*(:))|(-))\s*(?:((")[^"]*("))|((')[^']*('))|([^,{}&amp;#\[\]]+))\s*</string>
			<key>name</key>
			<string>meta.tag.yaml</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.entry.yaml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.yaml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.yaml</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.entry.yaml</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.yaml</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.yaml</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.yaml</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>string.quoted.single.yaml</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.yaml</string>
				</dict>
				<key>10</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.yaml</string>
				</dict>
				<key>11</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.yaml</string>
				</dict>
			</dict>
		</dict>

		<!-- Allow YAML keys to begin with / -->
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.yaml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.yaml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.other.omap.yaml</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.keyword.yaml</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.yaml</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([\w\/][^\:\#]*?)(:)\s*((\!\!)omap)?(.*)?</string>
			<key>name</key>
			<string>meta.tag.yaml</string>
		</dict>

		<dict>
			<key>include</key>
			<string>source.yaml</string>
		</dict>
	</array>
</dict>
</plist>
